name: Restaurant CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Mostrar archivos
        run: ls

      - name: Simular pruebas
        run: echo "Tests exitosos"

      - name: Simular Docker
        run: echo "Docker build exitoso"

      - name: Simular despliegue
        run: echo "Deploy realizado correctamente"